language: r
cache: packages

dist: trusty
sudo: required

r:
    - oldrel
    - release
    - devel

os:
    - linux
    - osx

matrix:
    fast_finish: true
    allow_failures:
        - r: devel

after_success:
  - Rscript -e 'covr::codecov()'

branches:
    only:
        - master
